spring:
  appliation:
    name: ewcms-server
    description: ewcms server application
    author: <a href="mailto:hhywangwei@gmail.com">WangWei</a>
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-siz: 12MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
      deserialization:
        FAIL_ON_UNKNOWN_PROPERTIES: false
      time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/ewcms_db
    repositories:
      type: none
    redis:
      repositories:
        enabled: false
  redis:
    url: redis://127.0.0.1:6379
    timeout: 10000
    pool:
      maxActive: 10
      maxIdle: 10
      maxWait: -1
      minIdle: 5


server:
  port: 8082
  compression:
    enabled: true
    mime-types: text/html,application/json

upload:
  max: 3
  root: /Users/weiwang/data
  baseUrl: http://127.0.0.1/file
  maxImageLength: 716800
  thumbWidth: 256
  thumbPrefix: _thumb_
  orgiPrefix: _orgi_